apiVersion: v1
kind: ConfigMap
metadata:
  name: hexagonal-payment-config
  namespace: payment
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  SPRING_DATASOURCE_URL: "jdbc:mysql://localhost:13306/hexagonal_payment?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
  SPRING_DATASOURCE_USERNAME: "payment_user"
  SPRING_DATA_REDIS_HOST: "localhost"
  SPRING_DATA_REDIS_PORT: "16379"
  SERVER_PORT: "10001"
  JAVA_OPTS: "-Xms512m -Xmx1024m -XX:+UseG1GC"
