# k8s/hexagonal-payment/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: hexagonal-payment-secret
  namespace: payment
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "payment123"
  SPRING_DATA_REDIS_PASSWORD: "admin123"
