apiVersion: v1
kind: Service
metadata:
  name: hexagonal-payment
  namespace: payment
spec:
  type: NodePort
  selector:
    app: hexagonal-payment
  ports:
    - name: http
      protocol: TCP
      port: 10001
      targetPort: 10001
#      nodePort: 30001
    - name: debug
      protocol: TCP
      port: 20002
      targetPort: 20002
#      nodePort: 30005
