spring:
  cloud:
    gateway:
      routes:
        - id: payment-service
          uri: http://localhost:10001
          predicates:
            - Path=/api/payments/**
          filters:
            - RewritePath=/api/payments/(?<segment>.*), /api/v1/${segment}
