# k8s/default-gateway/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secret
  namespace: default-gateway
type: Opaque
stringData:
  REDIS_PASSWORD: "admin123"
  JWT_SECRET: "my-super-secret-key-for-gateway"
  EXTERNAL_API_KEY: "external-api-key"
