# k8s/default-gateway/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: default-gateway        # ⭐ api-gateway → default-gateway
  namespace: default-gateway
  labels:
    app: default-gateway       # ⭐ 레이블도 통일
spec:
  type: LoadBalancer
  selector:
    app: default-gateway       # ⭐ selector도 통일
  ports:
    - name: http
      port: 10000
      targetPort: 10000
      protocol: TCP
#      nodePort: 30000
    - name: debug
      port: 20000
      targetPort: 20000
      protocol: TCP
#      nodePort: 30312
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
