server:
  port: 10001

spring:
  datasource:
    url: jdbc:mysql://localhost:13306/module?characterEncoding=UTF-8
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  batch:
    jdbc:
      initialize-schema: always  # 배치 메타데이터 테이블 자동 생성
    job:
      enabled: false  # 자동 실행 방지 (수동으로 실행)

  jpa:
    hibernate:
        ddl-auto: create
#        ddl-auto: update  # 기존 데이터 유지하면서 스키마 업데이트
#        ddl-auto: validate  # 스키마 검증만 수행
    defer-datasource-initialization: true
    properties:
      hibernate:
        jdbc:
          batch_size: 30
        order_inserts: true
        batch_versioned_data: true
        format_sql: true
    show-sql: false
  sql:
    init:
      # 이미 생성된 데이터 있을 경우
#       mode: never
      # 신규 생성시
       mode: always
       encoding: UTF-8
       data-locations:
        - classpath:data/user/user.sql
  data:
    redis:
      host: localhost
      port: 16379
      password: admin123
      timeout: 3000ms


logging:
  level:
    p6spy: info
    org.hibernate.SQL: off
    org.hibernate.type.descriptor.sql: off
