spring:
  datasource:
    # ✅ localhost → host.docker.internal
    url: jdbc:mysql://host.docker.internal:13306/hexagonal_payment?characterEncoding=UTF-8
    username: payment_user
    password: payment123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        jdbc:
          batch_size: 30
        order_inserts: true
        batch_versioned_data: true
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always
      encoding: UTF-8
      data-locations:
        - classpath:data/payment/payment.sql
  data:
    redis:
      # ✅ localhost → host.docker.internal
      host: host.docker.internal
      port: 16379
      password: admin123
      timeout: 3000ms

server:
  port: 10001

logging:
  level:
    p6spy: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
